# Generated by Django 5.2.3 on 2025-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='need_puzzle',
            field=models.BooleanField(default=False),
        ),
    ]
