# Generated by Django 5.2.4 on 2025-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0002_alter_survivor_options_alter_survivor_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='consecutive_even_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survivor',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
