# Generated by Django 5.2.3 on 2025-08-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('is_safe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('zombie_amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survivor_log', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField()),
                ('seen_zombie', models.BooleanField()),
                ('from_zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_zone_zone_connection', to='logs.zone')),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survivor_zone_connection', to=settings.AUTH_USER_MODEL)),
                ('to_zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_zone_zone_connection', to='logs.zone')),
            ],
        ),
    ]
