# Generated by Django 5.2.4 on 2025-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('consecutive_even_numbers', models.IntegerField(default=0)),
            ],
        ),
    ]
