# Generated by Django 5.2.4 on 2025-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_puzzle_survivor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='consecutive_even_numbers',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='is_suspicious',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='survivor',
        ),
        migrations.AddField(
            model_name='log',
            name='consecutive_even_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
