# Generated by Django 5.2.4 on 2025-08-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_puzzle_consecutive_even_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='consecutive_even_numbers',
        ),
        migrations.RemoveField(
            model_name='log',
            name='is_suspicious',
        ),
    ]
